SDK changes for Import Campaign API
plivo/plivo-php pull request #338
Opened 2024-02-19 12:02 UTC by vinaykumar-plivo

2024-02-21 12:12 UTC, Sajal-Singhal commented on src/Plivo/Version.php
> +    const MINOR = 60;
@vinaykumar-plivo can you pls make patch version 0 below

2024-02-22 05:33 UTC, Sajal-Singhal approved these changes
LGTM

2024-03-07 11:31 UTC, rajneeshkatkam-plivo approved these changes

2024-03-11 06:47 UTC, narayana-plivo commented on src/Plivo/BaseClient.php
> +    public function importCamp($uri, $params)
why do we need this function in baseClient?

2024-03-11 06:48 UTC, narayana-plivo commented on src/Plivo/Resources/Campaign/CampaignInterface.php
> +    public function importcampaign($campaignId,$campaign_alias)
we need to add optional param on function signature.

2024-03-11 06:49 UTC, narayana-plivo commented on src/Plivo/Resources/Campaign/CampaignInterface.php
> +        $response = $this->client->importCamp(
cant we use client->update here?

2024-03-11 06:49 UTC, narayana-plivo requested changes
please address the review the comment

2024-03-12 06:51 UTC, narayana-plivo approved these changes

2024-03-13 10:56 UTC, merged